apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  selector:
      matchLabels:
        app.kubernetes.io/name: reverse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reverse-proxy
        service: reverse-proxy
    spec:
      containers:
      - image: bettafish15/reverseproxy:v1
        name: reverse-proxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always
