apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        service: frontend
        api: external
    spec:
      containers:
        - image: bettafish15/udagram-frontend:v2
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
