apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-user
        service: backend-user
    spec:
      containers:
        - image: bettafish15/udagram-api-user:v1
          name: backend-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "250m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
      restartPolicy: Always
